#server: 
#  port: ${random.int[10000,19999]}
 
spring:
  application:
    name: usc
#  #配置spring cloud bus
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: xjx
#    password: xjx
#    listener:
#      direct:
#        retry:
#          enabled: true
#      simple:
#        retry:
#          enabled: true
  datasource:
      name: test
      url: jdbc:mysql://192.168.6.201:3306/cloudIntegration
      username: root
      password: root
#  session:
#    store-type: redis
#    timeout: 30m        
#  redis:
#    host: 127.0.0.1
#    port: 6379
#  rabbitmq:
#    addresses: 127.0.0.1:5672
    
mybatis:
  config-location: classpath:mybatis-config.xml #配置 MyBatis 基础属性
  mapper-locations: classpath:org/alalgo/usc/mapper/*.xml #配置 Mappery映射文件位置
  type-aliases-package: org.alalgo.usc.model #配置项目中实体类包路径
   
   
logging:
  level:
    org.springframework.jdbc.datasource: debug
    org.alalgo: debug
  #配置quartz存储在数据库中，默认存储在内存中
 #quartz:
 #  job-store-type: jdbc
 #  jdbc:
 #    initialize-schema: always
      
    
#  #zipkin client 配置  
#  zipkin:
#    base-url: http://localhost:8092 #zipkin 服务器地址
#  sleuth:
#    sampler:
#      probability: 1.0
#  security:
#    user:
#      name: user
#      password: 123456
#          
#feign:
#  hystrix:
#    enabled: true   
    
#打开actuator/hystrix.stream访问路径    
#management: 
#  endpoints:
#    web:
#      exposure:
#        include: "*"        

#eureka: 
#  instance:
#    prefer-ip-address: true  # 注册服务的时候使用服务的ip地址
#  client:
#    service-url:
#      defaultZone: http://192.168.16.63:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true   
    
      
#debug: true 