server: 
  port: 8761
eureka: 
  instance: 
    hostname: eureka-server # eureka实例的主机名 
  client: 
    register-with-eureka: false #不把自己注册到eureka上 
    fetch-registry: false #是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。  
    service-url: 
      defaultZone: http://localhost:8761/eureka/ #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
