spring:
  application:
    name: consumer-ribbon
server: 
  port: 8200 
eureka: 
  instance: 
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
management: #打开actuator/hystrix.stream访问路径
  endpoints:
    web:
      exposure:
        include: "*"
